export const GET_COUNTRIES = 'GET_COUNTRIES';
export const ORDER_BY_NAME = 'ORDER_BY_NAME';
export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const POST_ACTIVITIES = 'POST_ACTIVITIES';
export const DETAIL = 'POST_ACTIVITIES';
export const SEARCH_COUNTRIES = 'SEARCH_COUNTRIES'